### ISSUE TITLE
Can't manipulate search field with keyboard

### ISSUE THREAD

**Issue by d-wid** [flathub/com.napster.napster-bigscreen-electron#1]
I'm hugely grateful that a Napster client is now available on Flatpak too. Unfortunately I can't manipulate the search field with my USB keyboard at all, instead I'm forced to click on the search page's on-screen keyboard to input or remove any character.

I'd really appreciate it if I could also use the keyboard to do that.
![Screenshot from 2022-08-21 23-43-29](https://user-images.githubusercontent.com/65876951/185812179-3a210c98-30fc-456e-bac3-d28352eb60c9.png)

**Comment by d-wid** [comment]
My bad, I don't think I should be asking about that here.

**Comment by mvgiacomello** [comment]
Hi, @d-wid thanks for the ticket. I am finishing moving the project over from our internal Napster repository to this one;
I'll bring your suggestion to the team!

**Comment by d-wid** [comment]
Thanks! so I guess I'll just reopen this one.

**Comment by mvgiacomello** [comment]
Hi @d-wid the team decided not to tackle this task at this point since this specific build is aimed at consoles and TVs.
The Napster team will be working on porting the Desktop version [(already available on Mac and Windows)](https://www.napster.com/gb/download/#) to Linux which will have a more Desktop look and feel.

**Comment by M4ST3R0FD1S4ST3R** [comment]
> Hi @d-wid the team decided not to tackle this task at this point since this specific build is aimed at consoles and TVs. The Napster team will be working on porting the Desktop version [(already available on Mac and Windows)](https://www.napster.com/gb/download/#) to Linux which will have a more Desktop look and feel.

If you don't mind answering or are able to answer can we get a estimate as to when this desktop Linux client will release? I can't seem to find a roadmap on the Napster website and given the age of this comment I would like to know if this is still in the works.
